#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

#define KC_COPY LCTL(KC_C)
#define KC_CUT LCTL(KC_X)
#define KC_PSTE LCTL(KC_V)
#define KC_UNDO LCTL(KC_Z)
#define KC_REDO RCS(KC_Z) 

#define DOT_EXLM LT(0,KC_DOT)
#define COMM_MINS LT(0,KC_COMM)
#define SLSH_UNDS LT(0,KC_SLSH)
#define SCLN_QUOT LT(0,KC_SCLN)
#define QUOT_SCLN LT(0,KC_QUOT)
#define P_QUOT LT(0,KC_P)

// layer aliases
#define _DEFAULT 0
#define _QWERTY 1
#define _MEDIA 2
#define _NAV 3
#define _MOUSE 4
#define _SYM 5
#define _NUM 6
#define _FUN 7

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// NOTE: Hue is flipped across 43-169 (Yellow-Blue) axis (see https://docs.qmk.fm/features/rgblight#color-selection)
layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    case _FUN:
        rgblight_sethsv (85, 255, 100); // Red
        break;
    case _NUM:
        rgblight_sethsv (169, 255, 100); // Blue
        break;
    case _SYM:
        rgblight_sethsv (0, 255, 100); // Green
        break;
    case _MOUSE:
        rgblight_sethsv (43, 255, 100); // Yellow
        break;
    case _NAV:
        rgblight_sethsv (201, 255, 100); // Cyan
        break;
    case _MEDIA:
        rgblight_sethsv (127, 255, 100); // Magenta
        break;
    default: //  for any other layers, or the default layer
        rgblight_sethsv (0, 0, 100); // White
        break;
    }
  return state;
}

// Helper for implementing tap vs. long-press keys. Given a tap-hold
// key event, replaces the hold function with `long_press_keycode`.
static bool process_tap_or_long_press_key(
    keyrecord_t* record, uint16_t long_press_keycode) {
  if (record->tap.count == 0) {  // Key is being held.
    if (record->event.pressed) {
      tap_code16(long_press_keycode);
    }
    return false;  // Skip default handling.
  }
  return true;  // Continue default handling.
}

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  switch (keycode) {
    case DOT_EXLM:  // Period on tap, Exlamation point on long press.
      return process_tap_or_long_press_key(record, S(KC_1));
    case COMM_MINS:  // Comma on tap, Minus on long press.
      return process_tap_or_long_press_key(record, KC_MINS);
    case SLSH_UNDS:  // Slash on tap, Underscore on long press.
      return process_tap_or_long_press_key(record, S(KC_MINS));
    case SCLN_QUOT:  // Semicolon on tap, Quote on long press.
      return process_tap_or_long_press_key(record, KC_QUOT);
    case QUOT_SCLN:  // Quote on tap, Semicolon on long press.
      return process_tap_or_long_press_key(record, KC_SCLN);
    case P_QUOT:  // P on tap, Quote on long press.
      return process_tap_or_long_press_key(record, KC_QUOT);
  }

  return true;
}

/* This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_DEFAULT] = LAYOUT_split_3x5_3(
    KC_Q, KC_D, KC_R, KC_W, KC_B, KC_J, KC_F, KC_U, KC_P, QUOT_SCLN, 
    LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_H), LSFT_T(KC_T), KC_G, KC_Y, RSFT_T(KC_N), LCTL_T(KC_E), LALT_T(KC_O), LGUI_T(KC_I), 
    KC_Z, KC_X, KC_M, KC_C, KC_V, KC_K, KC_L, COMM_MINS, DOT_EXLM, SLSH_UNDS, 
    LT(_MEDIA,KC_ESC), LT(_NAV,KC_SPC), LT(_MOUSE,KC_TAB), LT(_SYM,KC_ENT), LT(_NUM,KC_BSPC), LT(_FUN,KC_DEL)), // Default
    [_QWERTY] = LAYOUT_split_3x5_3(
    KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, P_QUOT, 
    LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), LCTL_T(KC_K), LALT_T(KC_L), LGUI_T(KC_SCLN), 
    KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, COMM_MINS, DOT_EXLM, SLSH_UNDS, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS), // Qwerty
    [_MEDIA] = LAYOUT_split_3x5_3(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, DF(_QWERTY), CG_SWAP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, DF(_DEFAULT), CG_NORM, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_TRNS, KC_NO, KC_NO, KC_MSTP, KC_MPLY, KC_MUTE), // Media
    [_NAV] = LAYOUT_split_3x5_3(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_REDO, KC_PSTE, KC_COPY, KC_CUT, KC_UNDO, 
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_TRNS, KC_CAPS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, 
    KC_NO, KC_TRNS, KC_NO, KC_ENT, KC_BSPC, KC_DEL), // Nav
    [_MOUSE] = LAYOUT_split_3x5_3(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_TRNS, KC_TRNS, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, 
    KC_TRNS, MS_ACL2, MS_ACL1, MS_ACL0, KC_TRNS, KC_TRNS, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, 
    KC_NO, KC_NO, KC_TRNS, MS_BTN2, MS_BTN1, MS_BTN3), // Mouse
    [_SYM] = LAYOUT_split_3x5_3(
    S(KC_LBRC), S(KC_7), S(KC_8), S(KC_9), S(KC_RBRC), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    S(KC_SCLN), S(KC_4), S(KC_5), S(KC_6), S(KC_EQL), KC_TRNS, KC_RSFT, KC_RCTL, KC_RALT, KC_RGUI, 
    S(KC_GRV), S(KC_1), S(KC_2), S(KC_3), S(KC_BSLS), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    S(KC_9), S(KC_0), S(KC_MINS), KC_TRNS, KC_TRNS, KC_TRNS), // Sym
    [_NUM] = LAYOUT_split_3x5_3(
    KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_SCLN, KC_4, KC_5, KC_6, KC_EQL, KC_TRNS, KC_RSFT, KC_RCTL, KC_RALT, KC_RGUI, 
    KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_DOT, KC_0, KC_MINS, KC_TRNS, KC_TRNS, KC_TRNS), // Num
    [_FUN] = LAYOUT_split_3x5_3(
    KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_F11, KC_F4, KC_F5, KC_F6, KC_PAUS, KC_TRNS, KC_RSFT, KC_RCTL, KC_RALT, KC_RGUI, 
    KC_F10, KC_F1, KC_F2, KC_F3, KC_SCRL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
    KC_APP, KC_SPC, KC_TAB, KC_TRNS, KC_TRNS, KC_TRNS), // Fun
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



